# Generated by Django 5.0.3 on 2024-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
